### ISSUE TITLE
Crash when opening territory map on Wynncraft

### ISSUE THREAD

**Issue by cobalt2727** [gbl/AdvancementInfo#17]
Seems like their plugin messes with the achievements screen or something in order to make the map work.

```java
---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/26/22, 3:26 PM
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_167.method_731()" because the return value of "de.guntram.mcmod.advancementinfo.accessors.AdvancementWidgetAccessor.getProgress()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18+build.1)
	at de.guntram.mcmod.advancementinfo.AdvancementInfo.getSteps(AdvancementInfo.java:48)
	at net.minecraft.client.gui.screen.advancement.AdvancementsScreen.renderCriteria(AdvancementsScreen:749)
	at net.minecraft.client.gui.screen.advancement.AdvancementsScreen.handler$zzc000$renderRightFrameTitle(AdvancementsScreen:674)
	at net.minecraft.client.gui.screen.advancement.AdvancementsScreen.drawWindow(AdvancementsScreen:179)
	at net.minecraft.client.gui.screen.advancement.AdvancementsScreen.render(AdvancementsScreen:114)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:877)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at de.guntram.mcmod.advancementinfo.AdvancementInfo.getSteps(AdvancementInfo.java:48)
	at net.minecraft.class_457.renderCriteria(class_457.java:749)
	at net.minecraft.class_457.handler$zzc000$renderRightFrameTitle(class_457.java:674)
	at net.minecraft.class_457.method_2334(class_457.java:179)
	at net.minecraft.class_457.method_25394(class_457.java:114)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_457
	Mouse location: Scaled: (217, 116). Absolute: (653.000000, 348.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:877)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 71 total; [class_746['_cobalt27'/562517, l='ClientLevel', x=482.82, y=67.00, z=-1581.53], class_745['Atmisuki'/1141385559, l='ClientLevel', x=486.58, y=67.01, z=-1559.77], class_745['DopeShow666'/1141382945, l='ClientLevel', x=469.28, y=67.07, z=-1595.72], class_745['PlumPuddings'/1141381137, l='ClientLevel', x=485.41, y=67.07, z=-1596.16], class_745['Raqael'/1141300573, l='ClientLevel', x=473.53, y=67.01, z=-1569.47], class_745['Maronui'/1141382516, l='ClientLevel', x=441.83, y=67.27, z=-1603.07], class_745['LuckyMudStar'/1141384625, l='ClientLevel', x=492.70, y=68.88, z=-1551.67], class_745['Hysteria2651'/1141386228, l='ClientLevel', x=460.91, y=67.01, z=-1548.57], class_745['dsce'/1141380316, l='ClientLevel', x=486.52, y=67.07, z=-1594.57], class_745['Larree17'/1141385094, l='ClientLevel', x=467.14, y=67.01, z=-1590.30], class_745['Clatterpillar'/1141379176, l='ClientLevel', x=498.18, y=68.01, z=-1569.20], class_745['§'/14113, l='ClientLevel', x=491.50, y=67.00, z=-1574.50], class_745['§'/14222, l='ClientLevel', x=476.00, y=67.00, z=-1571.00], class_745['§'/567564, l='ClientLevel', x=466.50, y=67.00, z=-1573.50], class_745['MageGuy'/10441, l='ClientLevel', x=470.07, y=70.00, z=-1579.10], class_745['§'/256342, l='ClientLevel', x=501.50, y=68.00, z=-1569.50], class_745['§'/256338, l='ClientLevel', x=503.50, y=68.00, z=-1569.50], class_745['§'/14127, l='ClientLevel', x=487.45, y=67.00, z=-1560.54], class_745['§'/203953, l='ClientLevel', x=470.50, y=67.00, z=-1562.50], class_745['§'/203098, l='ClientLevel', x=471.00, y=67.00, z=-1566.00], class_745['§'/567569, l='ClientLevel', x=461.50, y=67.00, z=-1581.50], class_745['§'/567560, l='ClientLevel', x=480.50, y=67.00, z=-1609.50], class_745['§'/567554, l='ClientLevel', x=480.50, y=67.00, z=-1550.50], class_745['§'/259373, l='ClientLevel', x=475.42, y=67.00, z=-1551.49], class_745['§'/252558, l='ClientLevel', x=451.30, y=70.00, z=-1554.70], class_745['§'/204209, l='ClientLevel', x=456.50, y=67.00, z=-1560.50], class_745['§'/567582, l='ClientLevel', x=456.50, y=67.00, z=-1586.50], class_745['§'/257711, l='ClientLevel', x=513.70, y=67.00, z=-1612.30], class_745['§'/14591, l='ClientLevel', x=509.96, y=67.00, z=-1613.66], class_745['§'/16874, l='ClientLevel', x=516.00, y=67.00, z=-1598.00], class_745['§'/16872, l='ClientLevel', x=520.00, y=67.00, z=-1598.00], class_745['§'/18548, l='ClientLevel', x=455.30, y=67.00, z=-1613.14], class_745['§'/14137, l='ClientLevel', x=457.70, y=68.67, z=-1604.59], class_745['§'/14589, l='ClientLevel', x=460.42, y=67.00, z=-1614.56], class_745['§'/559742, l='ClientLevel', x=449.50, y=67.00, z=-1605.50], class_745['§'/261124, l='ClientLevel', x=511.92, y=67.06, z=-1612.98], class_745['§'/14135, l='ClientLevel', x=491.83, y=68.00, z=-1618.32], class_745['§'/14599, l='ClientLevel', x=435.30, y=71.00, z=-1591.30], class_745['§'/560316, l='ClientLevel', x=476.50, y=67.00, z=-1623.50], class_745['§'/257315, l='ClientLevel', x=500.00, y=67.00, z=-1629.00], class_745['§'/204352, l='ClientLevel', x=438.00, y=67.00, z=-1540.00], class_745['§'/559745, l='ClientLevel', x=437.50, y=67.00, z=-1602.50], class_745['§'/257309, l='ClientLevel', x=515.60, y=68.00, z=-1617.37], class_745['IlyALot'/1141379942, l='ClientLevel', x=468.25, y=67.07, z=-1594.07], class_745['DeathDoUsPart'/1141385228, l='ClientLevel', x=487.63, y=66.51, z=-1579.50], class_745['Dirt_ingot_'/388820, l='ClientLevel', x=464.80, y=67.00, z=-1593.65], class_745['Rokrihr'/563299, l='ClientLevel', x=466.13, y=67.50, z=-1595.42], class_745['NextSlow'/1141386296, l='ClientLevel', x=485.55, y=67.07, z=-1552.30], class_745['JustALlamaBoy'/1141294192, l='ClientLevel', x=470.61, y=67.07, z=-1595.43], class_745['Gaminyt'/1141386651, l='ClientLevel', x=474.12, y=67.68, z=-1566.17], class_745['G4lacticSnowman'/1141384598, l='ClientLevel', x=463.67, y=67.01, z=-1592.44], class_745['dogless'/1141386103, l='ClientLevel', x=461.76, y=67.07, z=-1569.80], class_745['Coffiibean'/1141386497, l='ClientLevel', x=483.51, y=67.01, z=-1556.61], class_745['GroovyFeelin'/1141385872, l='ClientLevel', x=475.62, y=67.07, z=-1597.97], class_745['SantaViBeS'/1141386478, l='ClientLevel', x=447.87, y=67.01, z=-1605.73], class_745['Doost44'/1141386747, l='ClientLevel', x=466.06, y=67.01, z=-1597.71], class_745['konman55'/1141386754, l='ClientLevel', x=476.98, y=67.07, z=-1571.84], class_745['xxicefeatherxx'/1141386793, l='ClientLevel', x=476.15, y=67.07, z=-1597.13], class_745['orenGr'/1141380351, l='ClientLevel', x=479.13, y=67.01, z=-1582.81], class_745['NeverDieHD'/1141382605, l='ClientLevel', x=500.25, y=68.01, z=-1569.99], class_745['Yelf_42'/1141386829, l='ClientLevel', x=462.92, y=67.51, z=-1577.51], class_745['Kofola0o7'/1141386784, l='ClientLevel', x=448.48, y=67.01, z=-1587.01], class_745['andrew12343'/1141372401, l='ClientLevel', x=477.80, y=67.17, z=-1576.43], class_745['MValeeP'/1141329417, l='ClientLevel', x=448.70, y=67.01, z=-1607.26], class_745['_P0ZA_'/1141385013, l='ClientLevel', x=465.86, y=67.01, z=-1574.32], class_745['RokRake'/562258, l='ClientLevel', x=462.76, y=37.00, z=-1559.97], class_745['Josh19'/1141381075, l='ClientLevel', x=483.80, y=67.01, z=-1555.45], class_745['Maus617'/1141384410, l='ClientLevel', x=485.09, y=68.18, z=-1560.26], class_745['Moloch_1'/1141383150, l='ClientLevel', x=490.78, y=68.51, z=-1556.79], class_745['IAMFallen_'/1141370885, l='ClientLevel', x=491.08, y=68.01, z=-1558.66], class_745['Someone_MC'/1141386953, l='ClientLevel', x=462.15, y=69.61, z=-1597.58]]
	Chunk stats: 16384, 338
	Level dimension: minecraft:overworld
	Level spawn location: World: (-1571,41,-1668), Section: (at 13,9,12 in -99,2,-105; chunk contains blocks -1584,0,-1680 to -1569,255,-1665), Region: (-4,-4; contains chunks -128,-128 to -97,-97, blocks -2048,0,-2048 to -1537,255,-1537)
	Level time: 5119017064 game time, 641780800 day time
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default, continuity/default, continuity/glass_pane_culling_fix, Mod Menu Helper.zip, lambdabettergrass/default, 1fb5f34624b7ccc557ab6a267273e8647e04d3c6

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 721265064 bytes (687 MiB) / 1363148800 bytes (1300 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.21
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1631
	Graphics card #1 name: NVIDIA GeForce GTX 1060
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1c20
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 17250.97
	Virtual memory used (MB): 12468.65
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 295.95
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		advancementinfo: AdvancementInfo 1.18.2-fabric0.47.10-1.3.1
		animatica: Animatica 0.4+1.18
		antighost: AntiGhost 1.18.2-fabric0.47.10-1.1.4
		architectury: Architectury 4.1.35
		autoconfig1u: Auto Config v1 Updated 3.2.2
		betterbeds: Better Beds 1.2.0
		bettermounthud: Better Mount HUD 1.1.4
		caffeineconfig: CaffeineConfig 1.0.0
		capes: Capes 1.2.2+1.18
		cem: Custom Entity Models 0.7.1
		chat_heads: Chat Heads 0.6.0
		citresewn: CIT Resewn 1.0.1+1.18.2
		citresewn-defaults: CIT Resewn: Defaults 1.0.1+1.18.2
		cloth-api: Cloth API 3.2.64
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 3.2.64
		cloth-common-events-v1: Cloth Common Events v1 3.2.64
		cloth-config: Cloth Config v6 6.2.57
		cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
		cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
		cloth-utils-v1: Cloth Utils v1 3.2.64
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		completeconfig: CompleteConfig 1.4.0
		continuity: Continuity 1.1.0+1.18.2
		crowdin-translate: CrowdinTranslate 1.4+1.18.2
		cullleaves: Cull Leaves 2.3.2
		dcch: DCCH 1.0
		dynamicfps: Dynamic FPS 2.1.0
		entity_texture_features: Entity Texture Features 2.5.13
		entityculling: EntityCulling-Fabric 1.5.0
		fabric: Fabric API 0.48.0+1.18.2
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.7+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.3+801ec85b60
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.2+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.13+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.3+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.10+3ac43d9560
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.4+d1027f7d60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.3+40c91ec860
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.17+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.2+d1027f7d60
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.14+40c91ec860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.14+cca23f9360
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+40c91ec860
		fabricloader: Fabric Loader 0.13.3
		fabrishot: Fabrishot ${version}
		fallingleaves: Falling Leaves 1.10.0+1.18.2
		farsight: Farsight Mod 1.18-1.8
		fastchest: FastChest 1.2+1.18
		fastopenlinksandfolders: FastOpenResourcePacks 1.1.0
		ferritecore: FerriteCore 4.2.0
		forgetmechunk: Forget Me Chunk 1.18.X-1.0.3
		indium: Indium 1.0.2+mc1.18.2
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.2-build.32
		itemmodelfix: Item Model Fix 1.0.3+1.18
		java: OpenJDK 64-Bit Server VM 17
		lambdabettergrass: LambdaBetterGrass 1.2.3+1.18
		lambdynlights: LambDynamicLights 2.1.0+1.17
		languagereload: Language Reload 1.2.1
		lazydfu: LazyDFU 0.1.2
		libzoomer: LibZoomer 0.4.0+1.18.2
		lithium: Lithium 0.7.9
		midnightlib: MidnightLib 0.4.0
		minecraft: Minecraft 1.18.2
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 3.1.0
		morechathistory: MoreChatHistory 1.1.0
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.2
		okzoomer: Ok Zoomer 5.0.0-beta.5+1.18.2
		org_anarres_jcpp: jcpp 1.4.14
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		pride: Pride Lib 1.1.0+1.17
		puzzle: Puzzle 1.2.1
		puzzle-base: Puzzle Base 1.2.1
		puzzle-gui: Puzzle GUI 1.2.1
		puzzle-models: Puzzle Models 1.2.1
		puzzle-splashscreen: Puzzle Splash Screen 1.2.1
		quilt_base: Quilt Base API 1.0.0+1.18.2-SNAPSHOT
		quilt_lifecycle_events: Quilt Lifecycle Events 1.0.0+1.18.2-SNAPSHOT
		quilt_resource_loader: Quilt Resource Loader 1.0.0+1.18.2-SNAPSHOT
		quilt_tags: Quilt Tags API 1.0.0+1.18.2-SNAPSHOT
		quilted-fabric-api-base: Quilted Fabric API Base 1.0.0+1.18.2-SNAPSHOT
		quilted-fabric-lifecycle-events-v1: Quilted Fabric Lifecycle Events (v1) 2.0.1+1.18.2-SNAPSHOT
		quilted-fabric-resource-loader-v0: Quilted Fabric Resource Loader (v0) 1.0.1+1.18.2-SNAPSHOT
		reeses-sodium-options: Reese's Sodium Options 1.4.2
		slight-gui-modifications: 'Slight' GUI Modifications 2.1.0
		smoothboot: Smooth Boot 1.18.2-1.7.0
		sodium: Sodium 0.4.1+build.15
		sodium-extra: Sodium Extra 0.4.2
		spruceui: SpruceUI 3.3.3+1.18
		starlight: Starlight 1.0.2+fabric.89b8d9f
		tiefix: TieFix 1.9.0
		tooltipfix: ToolTip Fix 1.0.4-1.18
		xaerominimap: Xaero's Minimap 22.4.0
		xaeroworldmap: Xaero's World Map 1.20.5
		yosbr: YOSBR 0.1.1
	Loaded Shaderpack: (off)
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 630 GL version 3.2.0 - Build 30.0.101.1631, Intel
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1282, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 173538523) Generic error' x 316
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, lambdabettergrass/default, continuity/default, continuity/glass_pane_culling_fix, file/Mod Menu Helper.zip, lambdabettergrass/default
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), AdvancementInfo (advancementinfo)
```

**Comment by Mikkel136** [comment]
**Can confirm; can reproduce.** This issue may relate to #15
This also applies to MC 1.19.x.

Caused by lack of error handling when AdvancementWidgetProcessor.getProgress() is nulled. 
Wynncraft relayes empty strings with custom NBT for visual purposes to the client while at the same time ignoring client-side requests. Unsure if this factor is related, but I'm pointing it out regardless.
